language: node_js
-node_js: 
      - "10"
-branches:
      only:
      - master
-before_script:
      - npm install -g ionic cordova
-script:
      - ionic cordova build browser --prod
-deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN 
      keep-history: true
      on:
            branch: master
            local_dir: www
